### ISSUE TITLE
[Enhancement] Max line length

### ISSUE THREAD

**Issue by kovetskiy** [mvdan/gofumpt#35] opened 2019-09-19 14:11 UTC
Hi!

Thanks for the project, it's really what I was looking for a long time! 

What do you think about implementing a sort of enforcement for max line length in Go in a way how google-java-format does it (splitting lines).

**Comment by mvdan** [comment] 2019-09-19 14:13
Duplicate of #2, sorry.

**Closed by mvdan** 2019-09-19 14:13 UTC
