### ISSUE TITLE
Consider an optional max line length breaking flag.

### ISSUE THREAD

**Issue by jaodsilv** [mvdan/gofumpt#207] opened 2022-03-15 20:52 UTC
Personally, one of the things that I hate the most when reading go code written by others that is not me is to understand long lines of code, especially if the person likes big variables/struct/function names.
I have ADHD and one solution I found to not be distracted by other stuff in computer when working was working in small screens, but, by the other hand, it makes a lot harder when I have to touch go code not written by me. So it would be lovely to have a line breaking. My suggestion is 100 chars if not configurable.

**Comment by mvdan** [comment] 2022-03-17 14:22
See https://github.com/mvdan/gofumpt/issues/2, which this issue is practically a duplicate of. Note that it's not planned to enforce an absolute hard limit on line length, primarily because it's not possible - some lines can't be broken up.

**Closed by mvdan** 2022-03-17 14:22 UTC
