### ISSUE TITLE
Enforce some consistency with newlines at the start and end of parameter lists

### ISSUE THREAD

**Issue by mmorel-35** [mvdan/gofumpt#262] opened 2023-02-24 18:41 UTC
I don’t see any linter proposing to remove trailing comma and new line between } and ),  so, I’m wondering if gofumpt would implement this rule.

So for example if I see 
```go
  myFunc(
    param1,
    myType{},
  )
```
I would expect to see this
```go
  myFunc(
    param1,
    myType{})
```
It seems like gofumpt accept either ways.
The linter is passing before and after my commit, [here](https://github.com/kumahq/kuma/pull/6126/commits/d9f215356ee5a63ba145fc743700347d3d049d55).

Would it be possible for gofumpt to provide this rule ?

**Comment by mvdan** [comment] 2023-04-08 16:19
We have the rule "Composite literals should use newlines consistently", which is similar but more aggressive. I think this makes sense. The only thing to note is that we shouldn't modify the following:

```
myFunc(param1,
    myType{})
```

That is, we would enforce newlines at both the start and end of the parameter list if either end has a newline already.

**Comment by mvdan** [comment] 2023-04-08 16:19
We could consider doing the same for function declarations too.

**Comment by mvdan** [comment] 2023-04-08 20:00
Actually a duplicate of https://github.com/mvdan/gofumpt/issues/74; I had already agreed to doing this :)

**Closed by mvdan** 2023-04-08 20:00 UTC
