### ISSUE TITLE
Gofumpt crashes when there is a file with a multiline function declaration which starts with a newline when the file is not the first file in the directory

### ISSUE THREAD

**Issue by mogzol** [mvdan/gofumpt#169] opened 2021-11-19 01:25 UTC
Sorry for the mess of a title, I don't really know how to describe it any better, so I'll just give an example of how to cause the crash:

1. Create a new empty directory
2. Within that directory, create two go files:
    - aaa.go:
      
      ````
      package example

      // This file's contents don't matter, but its name must cause it to come before the next file alphabetically
      ````
   - crash.go:
     
      ````
      package example
      
      func CrashGofumpt(a int,
      	b int) error {
      
      	return nil
      }
      ````
3. Now run `gofumpt .` within that directory. Gofumpt should crash:
      
    ````
   panic: invalid Pos value 1 (should be in [128, 201]) [recovered]
       panic: invalid Pos value 1 (should be in [128, 201])
   
   goroutine 1 [running]:
   golang.org/x/tools/go/ast/astutil.Apply.func1()
       /Users/morganzolob/go/pkg/mod/golang.org/x/tools@v0.1.8-0.20211102182255-bb4add04ddef/go/ast/astutil/rewrite.go:49 +0x89
   panic({0x12093a0, 0xc00010c790})
       /usr/local/go/src/runtime/panic.go:1038 +0x215
   go/token.(*File).Offset(0xc0001269c0, 0x2)
       /usr/local/go/src/go/token/position.go:281 +0xeb
   mvdan.cc/gofumpt/format.(*fumpter).addNewline(0xc000128640, 0xc00010c710)
       /Users/morganzolob/go/pkg/mod/mvdan.cc/gofumpt@v0.2.0/format/format.go:213 +0x3a
   mvdan.cc/gofumpt/format.(*fumpter).applyPre(0xc000128640, 0xc000126a90)
       /Users/morganzolob/go/pkg/mod/mvdan.cc/gofumpt@v0.2.0/format/format.go:558 +0x12f5
   mvdan.cc/gofumpt/format.File.func1(0xc000126a90)
       /Users/morganzolob/go/pkg/mod/mvdan.cc/gofumpt@v0.2.0/format/format.go:104 +0x3a
   golang.org/x/tools/go/ast/astutil.(*application).apply(0xc000126a80, {0x12943a0, 0xc00010ecc0}, {0x1247806, 0x18}, 0xc00012a9c8, {0x12940d0, 0xc00010ec90})
       /Users/morganzolob/go/pkg/mod/golang.org/x/tools@v0.1.8-0.20211102182255-bb4add04ddef/go/ast/astutil/rewrite.go:200 +0x202
   golang.org/x/tools/go/ast/astutil.(*application).apply(0xc000126a80, {0x1294350, 0xc000196280}, {0x1247a59, 0xc000196280}, 0x0, {0x12943a0, 0xc00010ecc0})
       /Users/morganzolob/go/pkg/mod/golang.org/x/tools@v0.1.8-0.20211102182255-bb4add04ddef/go/ast/astutil/rewrite.go:424 +0x17fd
   golang.org/x/tools/go/ast/astutil.(*application).applyList(0xc000126a80, {0x1294350, 0xc000196280}, {0x1247a59, 0x5})
       /Users/morganzolob/go/pkg/mod/golang.org/x/tools@v0.1.8-0.20211102182255-bb4add04ddef/go/ast/astutil/rewrite.go:479 +0xae
   golang.org/x/tools/go/ast/astutil.(*application).apply(0xc000126a80, {0x1294bc0, 0xc00010c770}, {0x124786a, 0x18}, 0x18, {0x1294350, 0xc000196280})
       /Users/morganzolob/go/pkg/mod/golang.org/x/tools@v0.1.8-0.20211102182255-bb4add04ddef/go/ast/astutil/rewrite.go:430 +0xb0d
   golang.org/x/tools/go/ast/astutil.Apply({0x1294350, 0xc000196280}, 0xc00011c1e0, 0xc00011c1f8)
       /Users/morganzolob/go/pkg/mod/golang.org/x/tools@v0.1.8-0.20211102182255-bb4add04ddef/go/ast/astutil/rewrite.go:54 +0x166
   mvdan.cc/gofumpt/format.File(0xc000128440, 0xc000196280, {{0xc00012a8fc, 0xc00014d600}, 0x94})
       /Users/morganzolob/go/pkg/mod/mvdan.cc/gofumpt@v0.2.0/format/format.go:152 +0x335
   main.processFile({0xc00012a960, 0x10}, {0x0, 0x0}, {0x12903c0, 0xc000124008}, 0x0)
       /Users/morganzolob/go/pkg/mod/mvdan.cc/gofumpt@v0.2.0/gofmt.go:130 +0x388
   main.visitFile({0xc00012a960, 0x10}, {0x1295e68, 0xc0001284c0}, {0x0, 0x0})
       /Users/morganzolob/go/pkg/mod/mvdan.cc/gofumpt@v0.2.0/gofmt.go:185 +0xf2
   path/filepath.walkDir({0xc00012a960, 0x10}, {0x1295e68, 0xc0001284c0}, 0x1256d78)
       /usr/local/go/src/path/filepath/path.go:386 +0x63
   path/filepath.walkDir({0x7ffeefbffb90, 0x7}, {0x1295ea0, 0xc00010c600}, 0x1256d78)
       /usr/local/go/src/path/filepath/path.go:405 +0x232
   path/filepath.WalkDir({0x7ffeefbffb90, 0x7}, 0x1256d78)
       /usr/local/go/src/path/filepath/path.go:469 +0xb0
   main.gofumptMain()
       /Users/morganzolob/go/pkg/mod/mvdan.cc/gofumpt@v0.2.0/gofmt.go:248 +0x405
   main.main()
       /Users/morganzolob/go/pkg/mod/mvdan.cc/gofumpt@v0.2.0/gofmt.go:195 +0x19
    ````

I've only tested this on an Intel MacBook with Go 1.17.3 installed, not sure if the same thing happens in other environments

**Comment by mvdan** [comment] 2021-11-19 10:24
Duplicate of https://github.com/mvdan/gofumpt/issues/166, perhaps? This is fixed in master - I just haven't done a point release yet.

**Comment by mvdan** [comment] 2021-11-19 14:15
Upon closer inspection, yes, it is a duplicate. Thanks for reporting!

**Closed by mvdan** 2021-11-19 14:15 UTC
