### ISSUE TITLE
Panic in v0.2.0

### ISSUE THREAD

**Issue by screwyprof** [mvdan/gofumpt#171] opened 2021-11-28 23:27 UTC
I've got a panic when I try to format the project. The older version didn't have such an issue. Do you happen to know if there's a quick workaround?

```shell
gofumpt -l -w ./...
```

```shell
panic: invalid Pos value 1 (should be in [2583733, 2586227]) [recovered]
        panic: invalid Pos value 1 (should be in [2583733, 25Ï86227])

goroutine 1 [running]:
golang.org/x/tools/go/ast/astutil.Apply.func1()
        /Users/happygopher/go/pkg/mod/golang.org/x/tools@v0.1.8-0.2Ï0211102182255-bb4add04ddef/go/ast/astutil/rewrite.go:49 +0x89
panic({0x12093a0, 0xc0000512f0})
        /usr/local/opt/go/libexec/src/runtime/panic.go:1038 +0x215
go/token.(*File).Offset(0xc00042daa0, 0x2)
        /usr/local/opt/go/libexec/src/go/token/position.go:281 +0xeb
mvdan.cc/gofumpt/format.(*fumpter).addNewline(0xc000113cc0, 0xc000491500)
        /Users/happygopher/go/pkg/mod/mvdan.cc/gofumpt@v0.2.0/format/format.go:213 +0x3a
mvdan.cc/gofumpt/format.(*fumpter).applyPre(0xc000113cc0, 0xc00042dc30)
        /Users/happygopher/go/pkg/mod/mvdan.cc/gofumpt@v0.2.0/format/format.go:558 +0x12f5
mvdan.cc/gofumpt/format.File.func1(0xc00042dc30)
        /Users/happygopher/go/pkg/mod/mvdan.cc/gofumpt@v0.2.0/format/format.go:104 +0x3a
golang.org/x/tools/go/ast/astutil.(*application).apply(0xc00042dc20, {0x12943a0, 0xc00012a9c0}, {0x1247806, 0x18}, 0xc00012e278, {0x12940d0, 0xc00012a990})
        /Users/happygopher/go/pkg/mod/golang.org/x/tools@v0.1.8-0.20211102182255-bb4add04ddef/go/ast/astutil/rewrite.go:200 +0x202
golang.org/x/tools/go/ast/astutil.(*application).apply(0xc00042dc20, {0x1294350, 0xc000491600}, {0x1247a59, 0xc000491600}, 0x0, {0x12943a0, 0xc00012a9c0})
        /Users/happygopher/go/pkg/mod/golang.org/x/tools@v0.1.8-0.20211102182255-bb4add04ddef/go/ast/astutil/rewrite.go:424 +0x17fd
golang.org/x/tools/go/ast/astutil.(*application).applyList(0xc00042dc20, {0x1294350, 0xc000491600}, {0x1247a59, 0x5})
        /Users/happygopher/go/pkg/mod/golang.org/x/tools@v0.1.8-0.20211102182255-bb4add04ddef/go/ast/astutil/rewrite.go:479 +0xae
golang.org/x/tools/go/ast/astutil.(*application).apply(0xc00042dc20, {0x1294bc0, 0xc0000512c0}, {0x124786a, 0x18}, 0x18, {0x1294350, 0xc000491600})
        /Users/happygopher/go/pkg/mod/golang.org/x/tools@v0.1.8-0.20211102182255-bb4add04ddef/go/ast/astutil/rewrite.go:430 +0xb0d
golang.org/x/tools/go/ast/astutil.Apply({0x1294350, 0xc000491600}, 0xc000198300, 0xc000198318)
        /Users/happygopher/go/pkg/mod/golang.org/x/tools@v0.1.8-0.20211102182255-bb4add04ddef/go/ast/astutil/rewrite.go:54 +0x166
mvdan.cc/gofumpt/format.File(0xc000186440, 0xc000491600, {{0xc00018cb40, 0xc000140000}, 0xa0})
        /Users/happygopher/go/pkg/mod/mvdan.cc/gofumpt@v0.2.0/format/format.go:152 +0x335
main.processFile({0x7ffeefbff0fb, 0x3c}, {0x0, 0x0}, {0x12903c0, 0xc000180008}, 0x0)
        /Users/happygopher/go/pkg/mod/mvdan.cc/gofumpt@v0.2.0/gofmt.go:130 +0x388
main.gofumptMain()
        /Users/happygopher/go/pkg/mod/mvdan.cc/gofumpt@v0.2.0/gofmt.go:242 +0x458
main.main()
        /Users/happygopher/go/pkg/mod/mvdan.cc/gofumpt@v0.2.0/gofmt.go:195 +0x19
```
go version go1.17.2 darwin/amd64

**Comment by mvdan** [comment] 2021-11-30 22:13
Looks like a dupe of https://github.com/mvdan/gofumpt/issues/166. I'll do a release soon - in the meantime, you can use master.

**Closed by mvdan** 2021-11-30 22:13 UTC
